#!/bin/bash
compile_proto () {
    echo "compiling $1"
    protoc -I ~/go/src/ --js_out=import_style=commonjs:./src/core/grpc-protos --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./src/core/grpc-protos $1
}

compile_model(){
    protoc -I ~/go/src/ --js_out=import_style=commonjs:./src/core/grpc-protos  --grpc-web_out=import_style=commonjs,mode=grpcwebtext:./src/core/grpc-protos ~/go/src/ /protos/model/*
}


echo "[compiling the rest]"
find ~/go/src/ /protos -name "*.proto" | while read file; do compile_proto $file; done
echo "[disabling eslint]"
find ./src/core/grpc-protos/  -name "*.js" -type f -exec sed -i.bk '1i \
/* eslint-disable */ ' {} \;
find ./src/core/grpc-protos/  -name "*.bk" -type f -delete
